import { lazy, Suspense, useMemo, useState } from 'react'
import { DEFAULT_VOYAGE, decodeRescueSave, type RescueState } from '@pongapp/game-core'
import { loadProfile, saveProfile } from './store'
import { RescueGame, downloadRescueSave } from './game/rescue/RescueGame'
import { SAVE_KEY, type RescueSessionOptions } from './game/rescue/RescueSession'
import { OfflinePack } from './game/rescue/OfflinePack'
import { VoyageWorkshop } from './game/VoyageWorkshop'
import './styles/starling.css'

const LegacyApp = lazy(() => import('./App'))
const SERVER = import.meta.env.VITE_ROOM_SERVER_URL || (import.meta.env.PROD ? 'https://pongapp-room.pongapp-room-worker.workers.dev' : 'http://127.0.0.1:8787')
function savedVoyage() { try { return decodeRescueSave(localStorage.getItem(SAVE_KEY) ?? '') } catch { return null } }
export default function StarlingApp() {
  const [profile, setProfile] = useState(loadProfile), [saved, setSaved] = useState(savedVoyage)
  const [voyage, setVoyage] = useState(DEFAULT_VOYAGE)
  const [legacy, setLegacy] = useState(() => /^#\/(room|race|classic)(\/|$)/i.test(location.hash))
  const [launch, setLaunch] = useState<{ online: boolean; code?: string; saved?: RescueState } | null>(() => { const code = /^#\/rescue\/([A-Z2-9]{6})$/i.exec(location.hash)?.[1]; return code ? { online: true, code: code.toUpperCase() } : null })
  const [code, setCode] = useState(''), [join, setJoin] = useState(false), [message, setMessage] = useState('')
  const options: RescueSessionOptions | null = useMemo(() => launch ? { name: profile.name, guestId: profile.id, server: SERVER, voyage, ...launch } : null, [launch, profile.name, profile.id, voyage])
  const home = () => { setLaunch(null); setSaved(savedVoyage()); history.replaceState(null, '', import.meta.env.BASE_URL) }
  const start = (online: boolean, continuing = false) => {
    if (!continuing) { try { const raw = localStorage.getItem(SAVE_KEY); if (raw) localStorage.setItem('starling-rescue.previous-save.v1', raw) } catch { /* previous save remains available for export */ } }
    setLaunch({ online, ...(continuing && saved ? { saved } : {}) })
  }
  if (legacy) return <><button className="sr-legacy-return" onClick={() => { setLegacy(false); history.replaceState(null, '', import.meta.env.BASE_URL) }}>← Starling Rescue</button><Suspense fallback={<div className="sr-loading">Opening classic voyages…</div>}><LegacyApp/></Suspense></>
  if (options) return <RescueGame options={options} onExit={home}/>
  return <div className="sr-home">
    <header className="sr-home-header"><a href={import.meta.env.BASE_URL} className="sr-brand"><span>✦</span><b>STARLING<small>RESCUE</small></b></a><div><button onClick={() => { setLegacy(true); history.replaceState(null, '', '#/classic') }}>Classic voyages</button><button onClick={() => setJoin(!join)}>Join a friend ↗</button></div></header>
    <main><section className="sr-hero"><div className="sr-hero-copy"><p className="sr-kicker">A SHIP FULL OF LITTLE SOULS</p><h1>Somewhere<br/>extraordinary.<br/><em>Together.</em></h1><p className="sr-lead">A tiny crew. A wonderfully impossible ship. Sail luminous seas, brave wild storms, and bring lost friends home.</p><div className="sr-launch-grid"><button className="sr-primary sr-launch" onClick={() => start(false)}><span>✦</span><b>Set sail</b><small>Play solo · your AI crew is aboard</small></button><button className="sr-launch" onClick={() => start(true)}><span>♧</span><b>Bring your people</b><small>Invite friends · shared adventure</small></button></div>{saved && <div className="sr-continue"><button onClick={() => start(false, true)}>Continue your voyage →</button><button onClick={() => start(true, true)}>Continue with friends</button><small>{saved.region} · {saved.stats.rescues}/5 rescued · {saved.crew.length} crew · {saved.campaign.salvage} salvage</small></div>}{join && <form className="sr-join" onSubmit={e => { e.preventDefault(); if (/^[A-Z2-9]{6}$/.test(code)) setLaunch({ online: true, code }); else setMessage('Enter the six-letter invitation code.') }}><input aria-label="Invitation code" placeholder="ROOM CODE" value={code} maxLength={6} onChange={e => setCode(e.target.value.toUpperCase())}/><button className="sr-primary" type="submit">Join ship</button></form>}<label className="sr-name"><span>Your name aboard</span><input maxLength={16} value={profile.name} onChange={e => { const next = { ...profile, name: e.target.value.replace(/[<>\u0000-\u001f]/g, '') || 'Explorer' }; setProfile(next); saveProfile(next) }}/></label><p className="sr-small">No signup. No purchases. Just a little courage.</p></div><div className="sr-hero-art"><div className="sr-orbit sr-orbit-one"/><div className="sr-orbit sr-orbit-two"/><span className="sr-hero-star star-one">✧</span><span className="sr-hero-star star-two">✦</span><img src={import.meta.env.BASE_URL + 'art/starling/observatory-hull.webp'} alt="A handcrafted coral and brass circular observatory ship"/><div className="sr-art-note"><span>THE STARLING</span><small>A home that goes wherever you do.</small></div></div></section>
    <section className="sr-features"><article><span>01 / A LITTLE TEAMWORK</span><h2>Find your station.</h2><p>Run, jump and climb between nine stations. Steer the engines, swing the shield, fire the cannons—or cook something good.</p></article><article><span>02 / A BIG LITTLE WORLD</span><h2>Beyond the horizon.</h2><p>Dock at towns and islands. Follow rivers into the jungle. Launch from a sky station into the stars.</p></article><article><span>03 / FRIENDS, NOT FOREVER</span><h2>Until we meet again.</h2><p>Rescue gifted crewmates. Share a voyage, say goodbye at a port, then reunite with an old friend somewhere new.</p></article></section>
    <section className="sr-save-section"><div><p className="sr-kicker">YOUR ADVENTURE GOES WITH YOU</p><h2>A voyage worth keeping.</h2><p>Automatic device saves, portable save files, and solo or shared continuation. Online rooms support up to eight humans and sixteen total crew.</p></div><div className="sr-save-actions"><label className="sr-file-button">Import a voyage<input type="file" accept=".json,application/json" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; if (file.size > 512000) { setMessage('This file is too large to be a voyage save.'); return }; const raw = await file.text(), imported = decodeRescueSave(raw); if (!imported) { setMessage('That save is damaged or belongs to an incompatible version. Your current save is unchanged.'); return }; try { const previous = localStorage.getItem(SAVE_KEY); if (previous) localStorage.setItem('starling-rescue.previous-save.v1', previous); localStorage.setItem(SAVE_KEY, raw); setSaved(imported); setMessage('Voyage imported. Continue solo or bring your friends.') } catch { setMessage('Your device cannot store this save right now.') }; e.target.value = '' }}/></label><button disabled={!saved} onClick={() => { const raw = localStorage.getItem(SAVE_KEY); if (raw) downloadRescueSave(raw) }}>Export saved voyage</button></div></section>
    <OfflinePack/>
    <div className="sr-workshop"><VoyageWorkshop serverUrl={SERVER} pack={voyage} onPack={setVoyage}/><p className="sr-small">In Starling, these four recipe families dress six authored creature types. Names, colors, ornaments and bounded body/armor traits change; physics never waits on AI.</p></div>
    {message && <p role="status" className="sr-home-message">{message}</p>}
    </main><footer className="sr-home-footer"><span>STARLING RESCUE · A TWO OARS ADVENTURE</span><span>Original art. Original score. Made for getting lost together.</span></footer>
  </div>
}
